### ISSUE TITLE
how to verify jwt?

### ISSUE THREAD

**Issue by bback99** [emqx/emqx-auth-jwt#35]
Hello, 

I'm trying to understand how to connect android app to emqtt broker using jwt for authentication.

I've set up with emq-auth-jwt plugin and secret key, username and pwd(JWT), so looks it works.

However, even if I put any string as username and pwd like "1" or any string not JWT, it's also working.(suppose to be verified)

is it correct way to use jwt? 

Thanks!!!

**Comment by Francesko90** [comment]
You are right, I tested on my cluster and I have same problem

I'm not an expert on earlang or this plugin but maybe  the problem is here: https://github.com/emqtt/emq-auth-jwt/blob/master/src/emq_auth_jwt.erl#L37
Instead of using ignore them they cloud trow error `lager:error("JWT decode error:~p", [Reason]),`

@emqplus what do you think about it?

**Comment by bback99** [comment]
I think you are right.
we should throw error out if they failed.

but funny thing is even if ignore, why it succeeded?? curious!!

**Comment by terry-xiaoyu** [comment]
@bback99 @Francesko90. 
I'm sorry maybe I have misunderstood this problem.. Have you set the `mqtt.allow_anonymous = false` in etc/emq.conf ?

Any username/password will be accepted if it is set to `true` (default).

**Comment by Francesko90** [comment]
Hi @terry-xiaoyu 

I change work and I have not access to cluster, maybe @bback99 can answer you

**Comment by anton-pytel** [comment]
Hello all,

I am experiencing strange problem. I am getting this error:
```
22:42:46.772 [error] JWT decode error:{invalid_algorithm,rs256,<<"-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuCb2ekD+dI+i5s9i34aOW65IMVSB/s05AlyZtgEk/jM1kq6jLgpXtlO7WcVRVeohe1gDVecr8LMnhdMBT1zLdvXwej4y/MnTYg1SQXp4o71oofo+5ehVO+z091Kv0w0s1j8qQrM/sVIdInJ7wBA+lCfiml853Algm+RPjCPkPtWz8Xbi6B2lVoukv7rjn6qD+5aT2BgDA8PFAsdXbfENQpSuvaeg5t+2dhY9413v82DQdXigSGnYKaWRnYlndgnvQYw+Wdu+RUkjTjRdbec4Ayt2V1iMdolyNi3Dbg4/Ipx5haouvEGMrktYpQbkhRAuyCcNuxEdet8A3h5cQmchtQIDAQAB-----END PUBLIC KEY-----">>}
22:42:46.772 [error] Client(emq_jwt@172.17.0.1:37716): Username '21ee4aaf-fc93-4536-a9f6-c64c0bfc21a8' login failed for token_error
```
jwt.io webpages succesfully verifies the signature of my token, but emq is saying that I have invalid algorithm even though readme says that rs256 is supported. 

Any ideas?

I am using Keycloak as a "token provider".
Starting emq as docker:
docker run --rm -ti --name emq -p 18083:18083 -p 1883:1883 -p 4369:4369 -e EMQ_LOADED_PLUGINS="emq_auth_jwt" -e EMQ_AUTH__JWT__PUBKEY=/opt/emqttd/mypubkey emq:latest

Thank you in advance for any help
Regards
Anton

**Comment by abser** [comment]
Hi @anton-pytel ,
I am also having same problem. Did you get the clue what was wrong?
Thanks
Nurul

**Comment by abser** [comment]
@anton-pytel ,
I updated my broker to latest 2.3.11 release and now it is working fine.
Regards
Nurul

**Comment by anton-pytel** [comment]
@abser I also wanted to ask, because I saw new release, but I presumed you were using the latest, because we did not have time to check the latest. Thank you very much for your information.
