### ISSUE TITLE
Connect to mqtt with a single password character

### ISSUE THREAD

**Issue by nerdial** [emqx/emqx-auth-jwt#53]
Hello,
Recently i have come across some issues connecting to mqtt **while jwt auth is active**.
as matter of a fact, when i connect to emqtt with **simple password** for instance 123456,this will connect to it successfully. 
I am pretty sure that **mqtt.allow_anonymous** is **false** but any password is possible when i connect to mqtt. another thing is that when i set jwt token in password it works properly, even it checks the validity of the token but other characters will be passed.
**emqtt version  =>  docker version  emqx/emqx**

I checked this issue with tools  such as MQTT Clients apps for instance mqttBox and mqtt.js in javascript.

```

mqtt.connect(MQTT_SOCKET_ENDPOINT, {
                    clean: false,
                    clientId: 'client_id',
                    username : 'username',
                    password : '123456'
 })

```

if this is not a problem what am i missing ?
**was emqx-auth-jwt deleted from latest version of emqx ?** 

thank you in advance for your thoughtful answers.

**Comment by nerdial** [comment]
no answers yet ?

**Comment by Gilbert-Wong** [comment]
Hi, @nerdial , so sorry for late respone , could you please tell me which emqx version did you try with, and could you please give me some logs when this issue happend.

**Comment by nerdial** [comment]
**EMQ X Broker : docker contianer - 3.0-rc.3**
Unfortunately there isn't  any error when the issue happend.as matter a of fact the only log i might give you is when no password is set  so **std-out** is s.th like this : 

`(8a3918021ffd@172.24.0.12)1> 2019-01-20 07:32:13.928 [error] nerdial1547969502812@172.24.0.1:46770 [MQTT] Username 'nerdial' login failed for token_undefined`

as soon as i set any character as password error will disappear and it connects to broker successfully.

**Comment by nerdial** [comment]
is there anything else i can help with ?
