### ISSUE TITLE
Option to pass the jwt pubkey through environment variable

### ISSUE THREAD

**Issue by agandrabur** [emqx/emqx-auth-jwt#73]
I am suggesting an enhancement. The config file has option to configure `auth.jwt.pubkey` like this:
```
## RSA or ECDSA public key file.
##
## Value: File
auth.jwt.pubkey = etc/certs/jwt_public_key.pem
```
which can be passed as env var to EMQX like this:
`EMQX_AUTH__JWT__PUBKEY="etc/certs/jwt_public_key.pem"`

It would be nice if you could pass the value of the key through the env var (maybe detect if it's a path in the filesystem or a certificate) like this `EMQX_AUTH__JWT__PUBKEY="MIIBIjA..AB"`.

We are deploying EMQX with docker and I can use the official image to configure everything related to `emqx-auth-http` through env vars, but for this plugin I have to create a new docker image just to add the certificate file.

**Comment by turtleDeng** [comment]
@agandrabur 
Thank you for your comments, we will not implement this feature, you can solve your problem by using docker's mount file.
